version: '3'
services:
  postgres:
    container_name: 'nestjs-postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - /tmp/postgres:/data/postgres
    env_file:
      - docker.env
  pgadmin:
    links:
      - postgres:postgres
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: always
    volumes:
      - /tmp/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
#    test